### ISSUE TITLE
Inference Network Question

### ISSUE THREAD

**Issue by na-dong** [conormdurkan/neural-statistician#1]
Hello, thanks for sharing code.
While reading Inference Network part, I want to know about the reasone that you add (z,c,h) instead of concatenating as mentioned in the paper pseudo code. 
Thanks.

**Comment by conormdurkan** [comment]
There’s no particular reason, and I don’t think there’s much practical difference between the two. One advantage of addition over concatenation is that it saves on parameters. You could try out concatenation, but I’m pretty sure it won't change anything.

**Comment by na-dong** [comment]
Thanks for the reply.
